/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef ENGINE_VERSION_H
#define ENGINE_VERSION_H

#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 2
#define ENGINE_VERSION_PATCH 0
#define ENGINE_VERSION_STRING "0.2.0"

#endif /* ENGINE_VERSION_H */
