; SPDX-License-Identifier: GPL-2.0-or-later
;
; Engine heartbeat — init/tick/shutdown, subsystem manager, plugin loader, and
; the "index" executable that becomes index.html/.js/.wasm under Emscripten.
;
; The WASM-specific shape of the "index" target — the extra plugin_abi.c source,
; the .html suffix, the shell/pre-js and the main-module link flags — is owned
; by the emitter (krudd/ninja/ninja.scm: the main_module rule and mainflags),
; not spelled here; version.h / shell.html are generated by
; krudd/introspect.scm's configure_file at synthesis time.
((library "subsystem"
	(sources "subsystem.c")
	(public "include"))

 (library "subsystem_manager"
	(sources "subsystem_manager.c")
	(public "include"))

 (library "plugin_loader"
	(sources "plugin_loader.c")
	(public "include")
	(private (root "modules/log/include") (root "plugins/include")))

 (executable "index"
	(sources "engine.c")
	(private "include" (raw "${generated}")
		(root "plugins/include"))
	(link "subsystem" "subsystem_manager" "log" "memory" "plugin_loader"))

 (native-only
	(executable "subsystem_test"
		(sources "subsystem_test.c")
		(link "subsystem"))
	(test "subsystem" "subsystem_test")

	(executable "subsystem_manager_test"
		(sources "subsystem_manager_test.c")
		(link "subsystem_manager"))
	(test "subsystem_manager" "subsystem_manager_test")

	(executable "plugin_loader_test"
		(sources "plugin_loader_test.c")
		(link "plugin_loader"))
	(test "plugin_loader" "plugin_loader_test")))
