; SPDX-License-Identifier: GPL-2.0-or-later
;
; cmake.scm — the CMake synthesizer.
;
; This is the first real organ of the strangler fig: instead of hand-writing
; CMakeLists.txt, we describe a directory's targets as Scheme data and render
; the CMake text from that description. krudd owns the spec; CMake is demoted to
; a backend we emit for. Over time more directories move behind the spec, and
; the day CMake itself is replaced, only this emitter changes — the specs stay.
;
; A directory spec is a list of target forms:
;
;   (library NAME clause...)      -> add_library(NAME ...)
;   (executable NAME clause...)   -> add_executable(NAME ...)
;   (test NAME COMMAND)           -> add_test(NAME NAME COMMAND COMMAND)
;   (native-only form...)         -> if(NOT EMSCRIPTEN) ... endif()
;
; Clauses shared by library/executable:
;
;   (sources SRC...)              source files
;   (public INC...)               PUBLIC include directories
;   (private INC...)              PRIVATE include directories
;   (link LIB...)                 PRIVATE link libraries (executables)
;
; A SRC/INC is either a bare string (relative to this directory) or
; (root "path"), which expands to ${CMAKE_SOURCE_DIR}/path for references that
; reach across the tree.

;; string list join — s7 has no string-join we can rely on.
(define (cmake-join sep lst)
  (cond ((null? lst) "")
	((null? (cdr lst)) (car lst))
	(else (string-append (car lst) sep (cmake-join sep (cdr lst))))))

;; Expand one source/include path spec to its CMake string.
(define (cmake-path p)
  (cond ((string? p) p)
	((and (pair? p) (eq? (car p) 'root))
	 (string-append "${CMAKE_SOURCE_DIR}/" (cadr p)))
	(else (error 'cmake-bad-path p))))

;; Find the clause whose head is HEAD, or #f.
(define (cmake-clause head clauses)
  (cond ((null? clauses) #f)
	((eq? (caar clauses) head) (car clauses))
	(else (cmake-clause head (cdr clauses)))))

;; Render "MACRO(NAME src src ...)". One source stays on a single line; several
;; break one-per-line with the close paren on its own line, matching house style.
(define (cmake-target-decl macro name srcs)
  (let ((paths (map cmake-path srcs)))
    (cond
      ((null? paths)
       (list (string-append macro "(" name ")")))
      ((null? (cdr paths))
       (list (string-append macro "(" name " " (car paths) ")")))
      (else
       (append
	 (list (string-append macro "(" name))
	 (map (lambda (p) (string-append "\t" p)) paths)
	 (list ")"))))))

;; target_include_directories(NAME VIS a b c) — nothing if the clause is absent.
(define (cmake-includes name clause vis)
  (if clause
      (list (string-append "target_include_directories(" name " " vis " "
			   (cmake-join " " (map cmake-path (cdr clause))) ")"))
      '()))

(define (cmake-emit-library form)
  (let* ((name    (cadr form))
	 (clauses (cddr form))
	 (sources (cmake-clause 'sources clauses)))
    (append
      (cmake-target-decl "add_library" name
			 (if sources (cdr sources) '()))
      (cmake-includes name (cmake-clause 'public clauses) "PUBLIC")
      (cmake-includes name (cmake-clause 'private clauses) "PRIVATE"))))

(define (cmake-emit-executable form)
  (let* ((name    (cadr form))
	 (clauses (cddr form))
	 (sources (cmake-clause 'sources clauses))
	 (link    (cmake-clause 'link clauses)))
    (append
      (cmake-target-decl "add_executable" name
			 (if sources (cdr sources) '()))
      (cmake-includes name (cmake-clause 'public clauses) "PUBLIC")
      (cmake-includes name (cmake-clause 'private clauses) "PRIVATE")
      (if link
	  (list (string-append "target_link_libraries(" name " PRIVATE "
			       (cmake-join " " (cdr link)) ")"))
	  '()))))

(define (cmake-emit-test form)
  (list (string-append "add_test(NAME " (cadr form)
		       " COMMAND " (caddr form) ")")))

;; Render one top-level form to a list of lines.
(define (cmake-emit-form form)
  (case (car form)
    ((library)     (cmake-emit-library form))
    ((executable)  (cmake-emit-executable form))
    ((test)        (cmake-emit-test form))
    ((native-only) (cmake-emit-native-only form))
    (else (error 'cmake-unknown-form form))))

(define (cmake-emit-native-only form)
  (let ((inner (apply append (map cmake-emit-form (cdr form)))))
    (append
      (list "if(NOT EMSCRIPTEN)")
      (map (lambda (l) (if (string=? l "") l (string-append "\t" l))) inner)
      (list "endif()"))))

(define cmake-header
  (string-append
    "# Generated by krudd — do not edit by hand.\n"
    "# Source of truth: krudd/build.scm, synthesized via krudd/cmake.scm.\n"
    "# Regenerate: ./krudd.sh build\n"
    "\n"))

;; Synthesize a directory spec to CMakeLists.txt text. Top-level forms are
;; separated by a blank line; the trailing newline keeps the file POSIX-clean.
(define (cmake-synthesize spec)
  (string-append
    cmake-header
    (cmake-join "\n\n"
		(map (lambda (form) (cmake-join "\n" (cmake-emit-form form)))
		     spec))
    "\n"))
