; SPDX-License-Identifier: GPL-2.0-or-later

;;! The chess scene — a full set in the standard opening position, the visual
;;! showcase for the engine's lathed meshes and PBR materials. Authored the way
;;! games/tictactoe/scene.scm is: one static (scene ...) form of (entity ...)
;;! declarations the engine's scene-build walks (core/scene_script.scm), each
;;! binding a builtin mesh + material and an authored transform. There is no
;;! game logic here and none alongside it — this slice is a set to look at, not
;;! a rules engine (see games/chess/chess.c); a later slice can add moves.
;;!
;;! Layout: files a..h run along +X (x = file - 3.5), ranks 1..8 along Z with
;;! white's first rank nearest the camera at z = +3.5 and black's at z = -3.5
;;! (z = 3.5 - rank). Squares are one unit, so a piece drops straight onto a
;;! square centre. a1 is dark: a square is dark when file+rank is even.
;;!
;;! The pieces are the six builtin://mesh/chess-* lathed/blocky meshes (see
;;! abi/builtin_mesh_scripts.h), authored foot-on-y=0 so they sit at the board
;;! top (y = 0.03). White wears builtin://material/chess-ivory, black
;;! chess-ebony. Knights face the enemy: the mesh faces +Z, so white's knights
;;! (high Z) are turned 180 to face -Z while black's keep the default. Each king
;;! carries its cross as two small crossed boxes (children), the way tic-tac-toe
;;! builds its X — a lathe cannot turn a cross.
;;!
;;! The board is 64 plane tiles (builtin://mesh/plane, board-light/board-dark)
;;! riding just above a walnut slab (a scaled box), the whole set resting on a
;;! wide matte ground plane. The "Camera" entity parks the eye high and to one
;;! side for a fixed 3/4 view; scene_renderer reads its world position as the
;;! camera eye each frame (the view target stays the origin, the board centre).

(scene chess
       (entity (name "Camera") (at 5.5 8.5 10.5))

       ;;! A wide matte ground the set rests on, then the walnut board slab (top at
       ;;! y = 0); the 64 tiles ride at y = 0.02 with a hair of grout showing the slab.
       (entity (name "ground")
               (mesh     "builtin://mesh/plane")
               (material "builtin://material/pbr-stone")
               (at 0 -0.34 0) (scale 30 1 30))
       (entity (name "board-base")
               (mesh     "builtin://mesh/box")
               (material "builtin://material/board-dark")
               (at 0 -0.16 0) (scale 8.6 0.32 8.6))

       ;;! The 64 playing squares.
       (entity (name "sq-a1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -3.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-b1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -2.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-c1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -1.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-d1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -0.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-e1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 0.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-f1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 1.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-g1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 2.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-h1") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 3.5 0.02 3.5) (scale 0.97 1 0.97))
       (entity (name "sq-a2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -3.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-b2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -2.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-c2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -1.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-d2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -0.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-e2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 0.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-f2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 1.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-g2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 2.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-h2") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 3.5 0.02 2.5) (scale 0.97 1 0.97))
       (entity (name "sq-a3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -3.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-b3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -2.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-c3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -1.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-d3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -0.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-e3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 0.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-f3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 1.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-g3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 2.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-h3") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 3.5 0.02 1.5) (scale 0.97 1 0.97))
       (entity (name "sq-a4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -3.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-b4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -2.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-c4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -1.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-d4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -0.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-e4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 0.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-f4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 1.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-g4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 2.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-h4") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 3.5 0.02 0.5) (scale 0.97 1 0.97))
       (entity (name "sq-a5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -3.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-b5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -2.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-c5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -1.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-d5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -0.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-e5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 0.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-f5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 1.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-g5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 2.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-h5") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 3.5 0.02 -0.5) (scale 0.97 1 0.97))
       (entity (name "sq-a6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -3.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-b6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -2.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-c6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -1.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-d6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -0.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-e6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 0.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-f6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 1.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-g6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 2.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-h6") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 3.5 0.02 -1.5) (scale 0.97 1 0.97))
       (entity (name "sq-a7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -3.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-b7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -2.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-c7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -1.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-d7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -0.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-e7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 0.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-f7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 1.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-g7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 2.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-h7") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 3.5 0.02 -2.5) (scale 0.97 1 0.97))
       (entity (name "sq-a8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -3.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-b8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -2.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-c8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at -1.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-d8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at -0.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-e8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 0.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-f8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 1.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-g8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-light") (at 2.5 0.02 -3.5) (scale 0.97 1 0.97))
       (entity (name "sq-h8") (mesh "builtin://mesh/plane")
               (material "builtin://material/board-dark") (at 3.5 0.02 -3.5) (scale 0.97 1 0.97))

       ;;! White army (ivory) on ranks 1-2, nearest the camera.
       (entity (name "wR-a1") (mesh "builtin://mesh/chess-rook")
               (material "builtin://material/chess-ivory") (at -3.5 0.03 3.5))
       (entity (name "wN-b1") (mesh "builtin://mesh/chess-knight")
               (material "builtin://material/chess-ivory") (at -2.5 0.03 3.5) (rotate 0 180 0))
       (entity (name "wB-c1") (mesh "builtin://mesh/chess-bishop")
               (material "builtin://material/chess-ivory") (at -1.5 0.03 3.5))
       (entity (name "wQ-d1") (mesh "builtin://mesh/chess-queen")
               (material "builtin://material/chess-ivory") (at -0.5 0.03 3.5))
       (entity (name "wK-e1")
               (mesh "builtin://mesh/chess-king") (material "builtin://material/chess-ivory")
               (at 0.5 0.03 3.5)
               (children
                (entity (mesh "builtin://mesh/box") (material "builtin://material/chess-ivory")
                        (at 0 1.55 0) (scale 0.05 0.24 0.05))
                (entity (mesh "builtin://mesh/box") (material "builtin://material/chess-ivory")
                        (at 0 1.57 0) (scale 0.17 0.05 0.05))))
       (entity (name "wB-f1") (mesh "builtin://mesh/chess-bishop")
               (material "builtin://material/chess-ivory") (at 1.5 0.03 3.5))
       (entity (name "wN-g1") (mesh "builtin://mesh/chess-knight")
               (material "builtin://material/chess-ivory") (at 2.5 0.03 3.5) (rotate 0 180 0))
       (entity (name "wR-h1") (mesh "builtin://mesh/chess-rook")
               (material "builtin://material/chess-ivory") (at 3.5 0.03 3.5))
       (entity (name "wP-a2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at -3.5 0.03 2.5))
       (entity (name "wP-b2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at -2.5 0.03 2.5))
       (entity (name "wP-c2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at -1.5 0.03 2.5))
       (entity (name "wP-d2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at -0.5 0.03 2.5))
       (entity (name "wP-e2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at 0.5 0.03 2.5))
       (entity (name "wP-f2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at 1.5 0.03 2.5))
       (entity (name "wP-g2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at 2.5 0.03 2.5))
       (entity (name "wP-h2") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ivory") (at 3.5 0.03 2.5))

       ;;! Black army (ebony) on ranks 7-8.
       (entity (name "bP-a7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at -3.5 0.03 -2.5))
       (entity (name "bP-b7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at -2.5 0.03 -2.5))
       (entity (name "bP-c7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at -1.5 0.03 -2.5))
       (entity (name "bP-d7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at -0.5 0.03 -2.5))
       (entity (name "bP-e7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at 0.5 0.03 -2.5))
       (entity (name "bP-f7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at 1.5 0.03 -2.5))
       (entity (name "bP-g7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at 2.5 0.03 -2.5))
       (entity (name "bP-h7") (mesh "builtin://mesh/chess-pawn")
               (material "builtin://material/chess-ebony") (at 3.5 0.03 -2.5))
       (entity (name "bR-a8") (mesh "builtin://mesh/chess-rook")
               (material "builtin://material/chess-ebony") (at -3.5 0.03 -3.5))
       (entity (name "bN-b8") (mesh "builtin://mesh/chess-knight")
               (material "builtin://material/chess-ebony") (at -2.5 0.03 -3.5))
       (entity (name "bB-c8") (mesh "builtin://mesh/chess-bishop")
               (material "builtin://material/chess-ebony") (at -1.5 0.03 -3.5))
       (entity (name "bQ-d8") (mesh "builtin://mesh/chess-queen")
               (material "builtin://material/chess-ebony") (at -0.5 0.03 -3.5))
       (entity (name "bK-e8")
               (mesh "builtin://mesh/chess-king") (material "builtin://material/chess-ebony")
               (at 0.5 0.03 -3.5)
               (children
                (entity (mesh "builtin://mesh/box") (material "builtin://material/chess-ebony")
                        (at 0 1.55 0) (scale 0.05 0.24 0.05))
                (entity (mesh "builtin://mesh/box") (material "builtin://material/chess-ebony")
                        (at 0 1.57 0) (scale 0.17 0.05 0.05))))
       (entity (name "bB-f8") (mesh "builtin://mesh/chess-bishop")
               (material "builtin://material/chess-ebony") (at 1.5 0.03 -3.5))
       (entity (name "bN-g8") (mesh "builtin://mesh/chess-knight")
               (material "builtin://material/chess-ebony") (at 2.5 0.03 -3.5))
       (entity (name "bR-h8") (mesh "builtin://mesh/chess-rook")
               (material "builtin://material/chess-ebony") (at 3.5 0.03 -3.5)))
