# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/engine/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/engine/engine/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/engine/engine/build/CMakeFiles /home/runner/work/engine/engine/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/engine/engine/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mimalloc-static

# Build rule for target.
mimalloc-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-static
.PHONY : mimalloc-static

# fast build rule for target.
mimalloc-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/mimalloc-build/CMakeFiles/mimalloc-static.dir/build.make _deps/mimalloc-build/CMakeFiles/mimalloc-static.dir/build
.PHONY : mimalloc-static/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) $(MAKESILENT) -f modules/log/CMakeFiles/log.dir/build.make modules/log/CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named memory

# Build rule for target.
memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory
.PHONY : memory

# fast build rule for target.
memory/fast:
	$(MAKE) $(MAKESILENT) -f modules/memory/CMakeFiles/memory.dir/build.make modules/memory/CMakeFiles/memory.dir/build
.PHONY : memory/fast

#=============================================================================
# Target rules for targets named subsystem

# Build rule for target.
subsystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 subsystem
.PHONY : subsystem

# fast build rule for target.
subsystem/fast:
	$(MAKE) $(MAKESILENT) -f modules/core/CMakeFiles/subsystem.dir/build.make modules/core/CMakeFiles/subsystem.dir/build
.PHONY : subsystem/fast

#=============================================================================
# Target rules for targets named subsystem_manager

# Build rule for target.
subsystem_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 subsystem_manager
.PHONY : subsystem_manager

# fast build rule for target.
subsystem_manager/fast:
	$(MAKE) $(MAKESILENT) -f modules/core/CMakeFiles/subsystem_manager.dir/build.make modules/core/CMakeFiles/subsystem_manager.dir/build
.PHONY : subsystem_manager/fast

#=============================================================================
# Target rules for targets named plugin_loader

# Build rule for target.
plugin_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 plugin_loader
.PHONY : plugin_loader

# fast build rule for target.
plugin_loader/fast:
	$(MAKE) $(MAKESILENT) -f modules/core/CMakeFiles/plugin_loader.dir/build.make modules/core/CMakeFiles/plugin_loader.dir/build
.PHONY : plugin_loader/fast

#=============================================================================
# Target rules for targets named index

# Build rule for target.
index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 index
.PHONY : index

# fast build rule for target.
index/fast:
	$(MAKE) $(MAKESILENT) -f modules/core/CMakeFiles/index.dir/build.make modules/core/CMakeFiles/index.dir/build
.PHONY : index/fast

#=============================================================================
# Target rules for targets named asset_plugin

# Build rule for target.
asset_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asset_plugin
.PHONY : asset_plugin

# fast build rule for target.
asset_plugin/fast:
	$(MAKE) $(MAKESILENT) -f plugins/asset/CMakeFiles/asset_plugin.dir/build.make plugins/asset/CMakeFiles/asset_plugin.dir/build
.PHONY : asset_plugin/fast

#=============================================================================
# Target rules for targets named asset_plugin_wasm

# Build rule for target.
asset_plugin_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asset_plugin_wasm
.PHONY : asset_plugin_wasm

# fast build rule for target.
asset_plugin_wasm/fast:
	$(MAKE) $(MAKESILENT) -f plugins/asset/CMakeFiles/asset_plugin_wasm.dir/build.make plugins/asset/CMakeFiles/asset_plugin_wasm.dir/build
.PHONY : asset_plugin_wasm/fast

#=============================================================================
# Target rules for targets named hello_plugin

# Build rule for target.
hello_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_plugin
.PHONY : hello_plugin

# fast build rule for target.
hello_plugin/fast:
	$(MAKE) $(MAKESILENT) -f plugins/hello_plugin/CMakeFiles/hello_plugin.dir/build.make plugins/hello_plugin/CMakeFiles/hello_plugin.dir/build
.PHONY : hello_plugin/fast

#=============================================================================
# Target rules for targets named renderer_null

# Build rule for target.
renderer_null: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 renderer_null
.PHONY : renderer_null

# fast build rule for target.
renderer_null/fast:
	$(MAKE) $(MAKESILENT) -f plugins/renderer_null/CMakeFiles/renderer_null.dir/build.make plugins/renderer_null/CMakeFiles/renderer_null.dir/build
.PHONY : renderer_null/fast

#=============================================================================
# Target rules for targets named renderer_null_wasm

# Build rule for target.
renderer_null_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 renderer_null_wasm
.PHONY : renderer_null_wasm

# fast build rule for target.
renderer_null_wasm/fast:
	$(MAKE) $(MAKESILENT) -f plugins/renderer_null/CMakeFiles/renderer_null_wasm.dir/build.make plugins/renderer_null/CMakeFiles/renderer_null_wasm.dir/build
.PHONY : renderer_null_wasm/fast

#=============================================================================
# Target rules for targets named renderer_webgl

# Build rule for target.
renderer_webgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 renderer_webgl
.PHONY : renderer_webgl

# fast build rule for target.
renderer_webgl/fast:
	$(MAKE) $(MAKESILENT) -f plugins/renderer_webgl/CMakeFiles/renderer_webgl.dir/build.make plugins/renderer_webgl/CMakeFiles/renderer_webgl.dir/build
.PHONY : renderer_webgl/fast

#=============================================================================
# Target rules for targets named renderer_webgl_wasm

# Build rule for target.
renderer_webgl_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 renderer_webgl_wasm
.PHONY : renderer_webgl_wasm

# fast build rule for target.
renderer_webgl_wasm/fast:
	$(MAKE) $(MAKESILENT) -f plugins/renderer_webgl/CMakeFiles/renderer_webgl_wasm.dir/build.make plugins/renderer_webgl/CMakeFiles/renderer_webgl_wasm.dir/build
.PHONY : renderer_webgl_wasm/fast

#=============================================================================
# Target rules for targets named frame_graph

# Build rule for target.
frame_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 frame_graph
.PHONY : frame_graph

# fast build rule for target.
frame_graph/fast:
	$(MAKE) $(MAKESILENT) -f plugins/frame_graph/CMakeFiles/frame_graph.dir/build.make plugins/frame_graph/CMakeFiles/frame_graph.dir/build
.PHONY : frame_graph/fast

#=============================================================================
# Target rules for targets named frame_graph_wasm

# Build rule for target.
frame_graph_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 frame_graph_wasm
.PHONY : frame_graph_wasm

# fast build rule for target.
frame_graph_wasm/fast:
	$(MAKE) $(MAKESILENT) -f plugins/frame_graph/CMakeFiles/frame_graph_wasm.dir/build.make plugins/frame_graph/CMakeFiles/frame_graph_wasm.dir/build
.PHONY : frame_graph_wasm/fast

#=============================================================================
# Target rules for targets named imgui_plugin_wasm

# Build rule for target.
imgui_plugin_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui_plugin_wasm
.PHONY : imgui_plugin_wasm

# fast build rule for target.
imgui_plugin_wasm/fast:
	$(MAKE) $(MAKESILENT) -f plugins/imgui_plugin/CMakeFiles/imgui_plugin_wasm.dir/build.make plugins/imgui_plugin/CMakeFiles/imgui_plugin_wasm.dir/build
.PHONY : imgui_plugin_wasm/fast

#=============================================================================
# Target rules for targets named kruddboard_wasm

# Build rule for target.
kruddboard_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kruddboard_wasm
.PHONY : kruddboard_wasm

# fast build rule for target.
kruddboard_wasm/fast:
	$(MAKE) $(MAKESILENT) -f plugins/kruddboard/CMakeFiles/kruddboard_wasm.dir/build.make plugins/kruddboard/CMakeFiles/kruddboard_wasm.dir/build
.PHONY : kruddboard_wasm/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... asset_plugin_wasm"
	@echo "... frame_graph_wasm"
	@echo "... hello_plugin"
	@echo "... imgui_plugin_wasm"
	@echo "... kruddboard_wasm"
	@echo "... renderer_null_wasm"
	@echo "... renderer_webgl_wasm"
	@echo "... asset_plugin"
	@echo "... frame_graph"
	@echo "... index"
	@echo "... log"
	@echo "... memory"
	@echo "... mimalloc-static"
	@echo "... plugin_loader"
	@echo "... renderer_null"
	@echo "... renderer_webgl"
	@echo "... subsystem"
	@echo "... subsystem_manager"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

