// SPDX-License-Identifier: GPL-2.0-or-later

//! `build-web` and `dist`: the Rust half, the TypeScript half, and the
//! directory a browser can be pointed at.
//!
//! The order matters and is the reason this is one command rather than two:
//! wasm-bindgen generates the JavaScript glue *and its `.d.ts`* from the
//! compiled wasm, and the TypeScript half imports that glue. Building TS
//! without regenerating the glue first would typecheck against a stale
//! boundary — the same "generated from without being rebuilt for" failure the
//! old tree's per-module `(embed …)` declarations existed to prevent.

use std::path::{Path, PathBuf};

use crate::Options;
use crate::sh::{self, Run};

/// Where wasm-bindgen writes the glue. Gitignored: it is regenerated by every
/// build, and it lives inside the boundary package rather than under
/// `target/` so TypeScript can import it by a stable relative path with its
/// types attached.
const GLUE_DIR: &str = "packages/base/boundary/generated";

/// The wasm-bindgen output basename.
const GLUE_NAME: &str = "krudd_web";

/// The published directory.
const DIST: &str = "dist";

/// What a build produced.
pub struct Artifacts {
    /// The `dist/` directory.
    pub dist: PathBuf,
}

/// Builds the wasm module and the TypeScript bundle into `dist/`.
pub fn build(opts: &Options) -> Result<Artifacts, String> {
    let root = sh::workspace_root();
    let version = sh::version(&root);
    println!("building krudd {version}");

    // Start from an empty dist/ so a leftover from a previous build — a
    // sourcemap a release build does not emit, a file a rename orphaned —
    // cannot be published as if this build produced it.
    let dist = root.join(DIST);
    if dist.exists() {
        std::fs::remove_dir_all(&dist).map_err(|e| format!("{}: {e}", dist.display()))?;
    }

    build_wasm(&root, &version, opts.release)?;
    run_wasm_bindgen(&root, opts.release)?;
    ensure_node_modules(&root, opts)?;
    bundle_typescript(&root, opts.release)?;
    assemble_dist(&root, &version)?;

    println!("built {}", dist.display());
    Ok(Artifacts { dist })
}

/// A release build, with the artifact sizes reported.
///
/// The sizes are printed because the wasm is fetched before anything can run:
/// a regression there is latency for every visitor, and a number nobody
/// prints is a number nobody notices.
pub fn dist(opts: &Options) -> Result<(), String> {
    let release = Options {
        release: true,
        port: opts.port,
        host: opts.host.clone(),
        skip_install: opts.skip_install,
    };
    let artifacts = build(&release)?;

    println!("\n{:<28} {:>10}", "artifact", "bytes");
    let mut entries: Vec<_> = std::fs::read_dir(&artifacts.dist)
        .map_err(|e| format!("{}: {e}", artifacts.dist.display()))?
        .filter_map(Result::ok)
        .collect();
    entries.sort_by_key(std::fs::DirEntry::file_name);
    for entry in entries {
        let size = entry.metadata().map(|m| m.len()).unwrap_or(0);
        println!(
            "{:<28} {size:>10}",
            entry.file_name().to_string_lossy(),
            size = size
        );
    }
    Ok(())
}

/// Compiles the shell crate to wasm.
fn build_wasm(root: &Path, version: &str, release: bool) -> Result<(), String> {
    let mut args = vec![
        "build",
        "--package",
        "krudd-web",
        "--target",
        "wasm32-unknown-unknown",
    ];
    if release {
        args.push("--release");
    }
    Run::cargo(root)
        .args(args)
        .env("KRUDD_VERSION", version)
        .check()
}

/// Runs wasm-bindgen over the compiled module, installing the CLI first if
/// the one on PATH is missing or the wrong version.
fn run_wasm_bindgen(root: &Path, release: bool) -> Result<(), String> {
    let wanted = locked_version(root, "wasm-bindgen")?;
    ensure_wasm_bindgen(root, &wanted)?;

    let profile = if release { "release" } else { "debug" };
    let wasm = root
        .join("target/wasm32-unknown-unknown")
        .join(profile)
        .join(format!("{GLUE_NAME}.wasm"));
    if !wasm.is_file() {
        return Err(format!("{} was not produced by cargo", wasm.display()));
    }

    Run::new("wasm-bindgen", root)
        .args([
            "--target",
            "web",
            "--out-dir",
            GLUE_DIR,
            "--out-name",
            GLUE_NAME,
            &wasm.to_string_lossy(),
        ])
        .check()
}

/// The version Cargo resolved for a dependency, read out of `Cargo.lock`.
///
/// The wasm-bindgen CLI and the `wasm-bindgen` crate must match exactly — a
/// mismatch produces a confusing "invalid schema version" at runtime rather
/// than an error at build time. Reading the lockfile rather than pinning a
/// literal means a `cargo update` cannot desynchronise them.
fn locked_version(root: &Path, crate_name: &str) -> Result<String, String> {
    let lock_path = root.join("Cargo.lock");
    let lock = sh::read(&lock_path)?;
    let needle = format!("name = \"{crate_name}\"");
    let mut lines = lock.lines();
    while let Some(line) = lines.next() {
        if line.trim() != needle {
            continue;
        }
        for line in lines.by_ref().take(3) {
            if let Some(version) = line.trim().strip_prefix("version = ") {
                return Ok(version.trim_matches('"').to_string());
            }
        }
    }
    Err(format!(
        "{}: no `{crate_name}` entry — run `cargo fetch` first",
        lock_path.display()
    ))
}

/// Installs the wasm-bindgen CLI if the one on PATH is not the wanted
/// version.
fn ensure_wasm_bindgen(root: &Path, wanted: &str) -> Result<(), String> {
    let found = Run::new("wasm-bindgen", root)
        .args(["--version"])
        .capture()
        .ok()
        .and_then(|out| out.split_whitespace().nth(1).map(str::to_string));

    if found.as_deref() == Some(wanted) {
        return Ok(());
    }
    match &found {
        Some(have) => println!("wasm-bindgen-cli {have} on PATH, but the crate is {wanted}"),
        None => println!("wasm-bindgen-cli is not on PATH"),
    }
    // `--locked` so installing the tool cannot pick up a newer transitive
    // dependency than the one it was released against.
    Run::cargo(root)
        .args([
            "install",
            "wasm-bindgen-cli",
            "--version",
            wanted,
            "--locked",
        ])
        .check()
}

/// Installs the TypeScript dependencies if they are missing.
fn ensure_node_modules(root: &Path, opts: &Options) -> Result<(), String> {
    if opts.skip_install || root.join("node_modules").is_dir() {
        return Ok(());
    }
    // `--frozen-lockfile` so a build can never silently resolve a different
    // dependency tree than the lockfile records. It is pnpm's default in CI
    // and not outside it; making it explicit means a local build fails the
    // same way CI would.
    Run::new("pnpm", root)
        .args(["install", "--frozen-lockfile"])
        .check()
}

/// Bundles the TypeScript entry point.
fn bundle_typescript(root: &Path, release: bool) -> Result<(), String> {
    let mut args = vec![
        "exec".to_string(),
        "esbuild".to_string(),
        "packages/shell/web/src/index.ts".to_string(),
        "--bundle".to_string(),
        "--format=esm".to_string(),
        "--platform=browser".to_string(),
        "--target=es2022".to_string(),
        format!("--outfile={DIST}/index.js"),
    ];
    if release {
        args.push("--minify".to_string());
    } else {
        args.push("--sourcemap".to_string());
    }
    Run::new("pnpm", root).args(args).check()
}

/// Copies the wasm and the page into `dist/`.
fn assemble_dist(root: &Path, version: &str) -> Result<(), String> {
    let dist = root.join(DIST);

    // The glue fetches this by name, relative to the page.
    sh::copy(
        &root.join(GLUE_DIR).join(format!("{GLUE_NAME}_bg.wasm")),
        &dist.join(format!("{GLUE_NAME}_bg.wasm")),
    )?;

    let template = root.join("packages/shell/web/index.html");
    let html = sh::read(&template)?.replace("__KRUDD_VERSION__", version);
    if html.contains("__KRUDD_") {
        return Err(format!(
            "{}: a __KRUDD_*__ placeholder was left unsubstituted",
            template.display()
        ));
    }
    sh::write(&dist.join("index.html"), &html)
}
