; SPDX-License-Identifier: GPL-2.0-or-later
((library "asset_plugin"
	(sources "asset_plugin.c" "asset_edit.c")
	(public "." (root "abi"))
	(link "log" "memory" "subsystem" "subsystem_manager" "m"))
 (native-only
	(executable "asset_test" (sources "asset_test.c")
		(link "asset_plugin" "log" "memory"))
	(test "asset" "asset_test")
	(executable "asset_codec_test" (sources "asset_codec_test.c")
		(link "asset_plugin" "log" "memory"))
	(test "asset_codec" "asset_codec_test")
	(executable "asset_api_test" (sources "asset_api_test.c")
		(link "asset_plugin" "log" "memory"))
	(test "asset_api" "asset_api_test")
	(executable "asset_mut_test" (sources "asset_mut_test.c")
		(link "asset_plugin" "log" "memory"))
	(test "asset_mut" "asset_mut_test")
	(executable "asset_edit_test"
		(sources "asset_edit_test.c" (root "edit/edit.c"))
		(private (root "edit"))
		(link "asset_plugin" "log" "memory"))
	(test "asset_edit" "asset_edit_test")
	(executable "asset_shader_test" (sources "asset_shader_test.c")
		(link "asset_plugin" "log" "memory"))
	(test "asset_shader" "asset_shader_test")
	(executable "asset_mesh_test" (sources "asset_mesh_test.c")
		(link "asset_plugin" "log" "memory"))
	(test "asset_mesh" "asset_mesh_test")

	(executable "mesh_script_test"
		(sources "mesh_script_test.c" "mesh_script.c")
		(private "." (root "abi") (raw "../third_party"))
		(link "script" "memory" "log"))
	(test "mesh_script" "mesh_script_test")))
