// SPDX-License-Identifier: GPL-2.0-or-later

/**
 * The wasm boundary: loading the Rust module, and reading its memory without
 * copying it.
 *
 * **Tier: `base`.** Depends on no other krudd package. Everything above it
 * talks to Rust through here rather than importing the generated glue
 * directly, so there is one place that knows how the module is loaded and one
 * place that knows when a typed-array view has gone stale.
 *
 * ## The one rule
 *
 * Calls into Rust are per *phase*, never per *object*. `tick()` advances the
 * whole world; `positions()` hands back a view over Rust's own memory. A
 * design that called across the boundary once per entity would be slow, and
 * it would look like "wasm is slow" rather than like the mistake it is. It is
 * measured, not asserted: `cargo xtask bench` puts the two paths side by side
 * and the batched one reads about 36× cheaper.
 *
 * The whole contract — ownership, what may be exported, and the three ways a
 * view goes stale — is `docs/boundary.md`. `harness/memory.test.ts` holds it
 * against the real module.
 *
 * ## Scope
 *
 * This module is hand-written, and the Rust half it mirrors is hand-written
 * too. Generating both sides from one spec so they cannot drift is #824;
 * until then, the pairing is checked by the fact that the generated `.d.ts`
 * this file imports is regenerated by every build.
 */

import init, { Engine, version } from "../generated/krudd_web.js";

/** How to boot the engine. */
export interface BootOptions {
	/**
	 * Where to fetch the wasm from. Relative to the page.
	 *
	 * The default matches what `cargo xtask build-web` writes into `dist/`.
	 */
	wasmUrl?: string;
	/** Canvas width in CSS pixels. */
	width: number;
	/** Canvas height in CSS pixels. */
	height: number;
	/**
	 * Device pixel ratio to scale by. Defaults to the window's, or 1 off the
	 * main thread.
	 */
	pixelRatio?: number;
}

/** A booted engine. */
export interface Krudd {
	/** The engine version the wasm was built at. */
	readonly version: string;
	/** The world. */
	readonly world: World;
}

/**
 * Boots the wasm module and returns a world.
 *
 * Idempotent per page: wasm-bindgen's `init` caches, so a second call returns
 * the already-instantiated module rather than fetching it again.
 */
export async function boot(options: BootOptions): Promise<Krudd> {
	const wasmUrl = options.wasmUrl ?? "./krudd_web_bg.wasm";
	const output = await init({ module_or_path: wasmUrl });
	const ratio = options.pixelRatio ?? globalThis.devicePixelRatio ?? 1;
	const engine = new Engine(
		Math.round(options.width * ratio),
		Math.round(options.height * ratio),
	);
	return {
		version: version(),
		world: new World(engine, output.memory),
	};
}

/**
 * The world, and the views over it.
 *
 * Wraps the generated `Engine` rather than re-exporting it so that the
 * lifetime rules around the memory views live in one place instead of at
 * every call site.
 */
export class World {
	readonly #engine: Engine;
	readonly #memory: WebAssembly.Memory;

	/**
	 * The cached position view, and the three facts that can invalidate it.
	 *
	 * `buffer` is in there because growing wasm memory *detaches* the old
	 * `ArrayBuffer`: every view over it becomes zero-length, silently. That is
	 * the failure this cache exists to prevent — a stale view does not throw,
	 * it just reads nothing, which looks exactly like an engine that stopped
	 * simulating.
	 */
	#positions: {
		view: Float32Array;
		ptr: number;
		length: number;
		buffer: ArrayBufferLike;
	} | null = null;

	/** Wraps an engine and the memory its pointers refer into. */
	constructor(engine: Engine, memory: WebAssembly.Memory) {
		this.#engine = engine;
		this.#memory = memory;
	}

	/** Spawns an entity at a position and returns its slot index. */
	spawn(x: number, y: number, z: number): number {
		return this.#engine.spawn(x, y, z);
	}

	/** Sets an entity's velocity in units per second. */
	setVelocity(slot: number, x: number, y: number, z: number): boolean {
		return this.#engine.set_velocity(slot, x, y, z);
	}

	/** Removes an entity. Returns whether the slot was live. */
	despawn(slot: number): boolean {
		return this.#engine.despawn(slot);
	}

	/** Advances the whole world by `dt` seconds — one call, not one per entity. */
	tick(dt: number): void {
		this.#engine.tick(dt);
	}

	/** Tells the engine the canvas resized, in CSS pixels. */
	resize(width: number, height: number, pixelRatio?: number): void {
		const ratio = pixelRatio ?? globalThis.devicePixelRatio ?? 1;
		this.#engine.resize(Math.round(width * ratio), Math.round(height * ratio));
	}

	/**
	 * The position column as a `Float32Array` over wasm memory: three floats
	 * per slot, indexed by the slot index `spawn` returned.
	 *
	 * The array is a **view, not a copy** — reading it after a `tick` sees the
	 * new positions with no call across the boundary. A `tick` cannot
	 * invalidate it; a `spawn` can, and so can anything that grows wasm
	 * memory. Fetch it where you use it and never store one in a field: it is
	 * three comparisons when nothing moved, and a silent correctness bug the
	 * day something does. See `docs/boundary.md`.
	 */
	positions(): Float32Array {
		const ptr = this.#engine.positions_ptr();
		const length = this.#engine.positions_len();
		const buffer = this.#memory.buffer;
		const cached = this.#positions;
		if (
			cached !== null &&
			cached.ptr === ptr &&
			cached.length === length &&
			cached.buffer === buffer
		) {
			return cached.view;
		}
		const view = new Float32Array(buffer, ptr, length);
		this.#positions = { view, ptr, length, buffer };
		return view;
	}

	/** The position of one entity, or `null` if the slot is not live. */
	positionOf(slot: number): [number, number, number] | null {
		if (slot >= this.slotCount) {
			return null;
		}
		const p = this.positions();
		const i = slot * 3;
		return [p[i] as number, p[i + 1] as number, p[i + 2] as number];
	}

	/** How many entities are live. */
	get entityCount(): number {
		return this.#engine.entity_count();
	}

	/** How many slots the position column covers, live and tombstoned alike. */
	get slotCount(): number {
		return this.#engine.slot_count();
	}

	/** How many times `tick` has been called. */
	get frameCount(): number {
		return this.#engine.frame_count();
	}

	/** Seconds of simulated time since boot. */
	get elapsed(): number {
		return this.#engine.elapsed();
	}

	/** The viewport size in physical pixels. */
	get viewport(): { width: number; height: number } {
		return { width: this.#engine.width(), height: this.#engine.height() };
	}
}
