// SPDX-License-Identifier: GPL-2.0-or-later

/**
 * The wasm boundary: loading the Rust module, and reading its memory without
 * copying it.
 *
 * **Tier: `base`.** Depends on no other krudd package. Everything above it
 * talks to Rust through here rather than importing the generated glue
 * directly, so there is one place that knows how the module is loaded and one
 * place that knows when a typed-array view has gone stale.
 *
 * ## The one rule
 *
 * Calls into Rust are per *phase*, never per *object*. `tick()` advances the
 * whole world; `positions()` hands back a view over Rust's own memory. A
 * design that called across the boundary once per entity would be slow, and
 * it would look like "wasm is slow" rather than like the mistake it is. It is
 * measured, not asserted: `cargo xtask bench` puts the two paths side by side
 * and the batched one reads about 36× cheaper.
 *
 * The whole contract — ownership, what may be exported, and the three ways a
 * view goes stale — is `docs/boundary.md`. `harness/memory.test.ts` holds it
 * against the real module.
 *
 * ## Scope
 *
 * This module is hand-written, and the Rust half it mirrors is hand-written
 * too. Generating both sides from one spec so they cannot drift is #824;
 * until then, the pairing is checked by the fact that the generated `.d.ts`
 * this file imports is regenerated by every build.
 */

import init, {
	type Engine,
	fit_drawing_buffer as fitDrawingBuffer,
	start,
	version,
} from "../generated/krudd_web.js";

/** How to boot the engine. */
export interface BootOptions {
	/**
	 * The canvas the engine draws into.
	 *
	 * Taken over for the lifetime of the engine: the WebGL2 context is created
	 * on it, and a canvas can only ever have one.
	 */
	canvas: HTMLCanvasElement;
	/**
	 * Where to fetch the wasm from. Relative to the page.
	 *
	 * The default matches what `cargo xtask build-web` writes into `dist/`.
	 */
	wasmUrl?: string;
	/**
	 * Device pixel ratio to scale the drawing buffer by. Defaults to the
	 * window's, or 1 off the main thread.
	 */
	pixelRatio?: number;
}

/**
 * Sizes a canvas's drawing buffer to its layout size times the pixel ratio —
 * or to the largest buffer the renderer can present, whichever is smaller —
 * and reports whether that changed anything.
 *
 * The one place that knows the difference between the two sizes a canvas has.
 * `canvas.style.width` is CSS pixels — what the page lays out — and
 * `canvas.width` is the drawing buffer, in physical pixels, which is what the
 * renderer allocates. Leaving them equal on a 2× display renders at half
 * resolution and upscales, which reads as "the engine is blurry" rather than
 * as a bug in sizing.
 *
 * The cap is not a nicety: a portrait phone at `devicePixelRatio` asks for a
 * buffer taller than the 2048 the WebGL2 backend can configure a surface
 * within, and that is a validation error that takes the page down rather than
 * a clamp that costs resolution. `fit_drawing_buffer` in the wasm module
 * decides the size, so the page and the renderer cannot fit to different
 * numbers and set the buffer back and forth at each other — which means this
 * function needs the module loaded, and `boot` is what guarantees that.
 *
 * Returns `false` when nothing changed, so a resize handler firing on every
 * frame of a drag does not reconfigure the swapchain each time.
 */
export function fitCanvas(
	canvas: HTMLCanvasElement,
	pixelRatio?: number,
): boolean {
	const ratio = pixelRatio ?? globalThis.devicePixelRatio ?? 1;
	// `clientWidth` is zero for a canvas that is not laid out yet — display
	// none, or a boot that ran before first layout. Clamping to 1 keeps the
	// drawing buffer legal; the next resize corrects it.
	const wanted = fitDrawingBuffer(
		Math.max(1, Math.round(canvas.clientWidth * ratio)),
		Math.max(1, Math.round(canvas.clientHeight * ratio)),
	);
	const width = wanted[0] as number;
	const height = wanted[1] as number;
	if (canvas.width === width && canvas.height === height) {
		return false;
	}
	canvas.width = width;
	canvas.height = height;
	return true;
}

/** A booted engine. */
export interface Krudd {
	/** The engine version the wasm was built at. */
	readonly version: string;
	/** The world. */
	readonly world: World;
}

/**
 * Boots the wasm module, attaches the renderer to the canvas, and returns a
 * world.
 *
 * Two awaits, and both are load-bearing: the first fetches and instantiates
 * the module, the second requests the GPU adapter and device. Neither can be
 * folded into a constructor, which is why the engine is reached through this
 * function rather than through `new`.
 *
 * Idempotent per page for the module — wasm-bindgen's `init` caches — but not
 * for the canvas: a second boot against the same canvas fails, because the
 * WebGL2 context is already taken.
 */
export async function boot(options: BootOptions): Promise<Krudd> {
	const wasmUrl = options.wasmUrl ?? "./krudd_web_bg.wasm";
	const output = await init({ module_or_path: wasmUrl });
	// Before `start`: the engine reads the canvas's drawing buffer size to size
	// its swapchain, so the buffer has to be right first.
	fitCanvas(options.canvas, options.pixelRatio);
	const engine = await start(options.canvas);
	return {
		version: version(),
		world: new World(engine, output.memory),
	};
}

/** The position column's name: three floats per slot, in world units. */
const POSITION = "position";

/** The velocity column's name: three floats per slot, in units per second. */
const VELOCITY = "velocity";

/**
 * One cached view over a column in wasm memory, and the three facts that can
 * invalidate it.
 *
 * `buffer` is in there because growing wasm memory *detaches* the old
 * `ArrayBuffer`: every view over it becomes zero-length, silently. That is the
 * failure this cache exists to prevent — a stale view does not throw, it just
 * reads nothing, which looks exactly like an engine that stopped simulating.
 *
 * One class rather than a pair of fields and a pair of comparisons per column,
 * because there is more than one column and the rule they are checked against
 * has to be the same rule whichever column it guards — `position`, `velocity`,
 * or a column a board declared itself. See `docs/boundary.md`.
 */
class Column {
	#cached: {
		view: Float32Array | Uint32Array;
		ptr: number;
		length: number;
		buffer: ArrayBufferLike;
	} | null = null;

	/**
	 * The column as a typed-array view over `memory`, rebuilt only when the
	 * address, the length or the buffer identity has changed.
	 *
	 * `ints` picks `Uint32Array` over `Float32Array`. It is fixed for the
	 * lifetime of the column this cache belongs to — a column's kind cannot
	 * change once created, because `ensure_column` refuses to reinterpret an
	 * existing one — so it never disagrees with what a cached view already is.
	 */
	view(
		memory: WebAssembly.Memory,
		ptr: number,
		length: number,
		ints: boolean,
	): Float32Array | Uint32Array {
		const buffer = memory.buffer;
		const cached = this.#cached;
		if (
			cached !== null &&
			cached.ptr === ptr &&
			cached.length === length &&
			cached.buffer === buffer
		) {
			return cached.view;
		}
		const view = ints
			? new Uint32Array(buffer, ptr, length)
			: new Float32Array(buffer, ptr, length);
		this.#cached = { view, ptr, length, buffer };
		return view;
	}
}

/**
 * The world, and the views over it.
 *
 * Wraps the generated `Engine` rather than re-exporting it so that the
 * lifetime rules around the memory views live in one place instead of at
 * every call site.
 */
export class World {
	readonly #engine: Engine;
	readonly #memory: WebAssembly.Memory;

	/**
	 * One cache per named column, keyed by name. `position` and `velocity`
	 * live in here too — they are ordinary columns the engine happens to
	 * create at boot, not a special case this map excludes.
	 */
	readonly #columns = new Map<string, Column>();

	/** Wraps an engine and the memory its pointers refer into. */
	constructor(engine: Engine, memory: WebAssembly.Memory) {
		this.#engine = engine;
		this.#memory = memory;
	}

	/** Spawns an entity at a position and returns its slot index. */
	spawn(x: number, y: number, z: number): number {
		return this.#engine.spawn(x, y, z);
	}

	/** Sets an entity's velocity in units per second. */
	setVelocity(slot: number, x: number, y: number, z: number): boolean {
		return this.#engine.set_velocity(slot, x, y, z);
	}

	/** Removes an entity. Returns whether the slot was live. */
	despawn(slot: number): boolean {
		return this.#engine.despawn(slot);
	}

	/**
	 * Empties the world — every entity, and every slot they left behind.
	 *
	 * One call for the whole world, which is the point: `despawn` per slot
	 * leaves a tombstone per slot, so a world emptied that way still reports
	 * the `slotCount` it had and anything sizing itself from that count builds
	 * the next scene on the last one's shape. Opening a different project is
	 * what wants this.
	 *
	 * Invalidates every column view, the same way a `spawn` can — fetch them
	 * again afterwards rather than reusing one taken before.
	 */
	clear(): void {
		this.#engine.clear();
	}

	/** Advances the whole world by `dt` seconds — one call, not one per entity. */
	tick(dt: number): void {
		this.#engine.tick(dt);
	}

	/**
	 * Tells the engine the canvas resized, in **physical** pixels.
	 *
	 * Physical rather than CSS pixels because that is what the renderer
	 * allocates, and because there is exactly one place that should know the
	 * conversion — `fitCanvas`. Pass it `canvas.width` and `canvas.height`.
	 *
	 * The engine may render at less than it is given, if the surface cannot be
	 * configured that large. `viewport` reports what it settled on.
	 */
	resize(width: number, height: number): void {
		this.#engine.resize(width, height);
	}

	/**
	 * Draws the world.
	 *
	 * Throws if the frame failed for a reason worth knowing about. A skipped
	 * frame — the surface went stale, the tab is in the background — is not one
	 * of those and returns normally.
	 */
	render(): void {
		this.#engine.render();
	}

	/**
	 * Presents a frame with nothing in it.
	 *
	 * The counterpart to `render`. A board whose paint lane runs nothing has to
	 * leave the screen showing *nothing* rather than the last frame it happened
	 * to draw — a canvas still holding a picture after the wire that drew it was
	 * cut says "working" and "did nothing" the same way.
	 */
	presentCleared(): void {
		this.#engine.present_cleared();
	}

	/**
	 * Sets how large one entity draws, in world units.
	 *
	 * One call for the whole world. A board's `scale` param reaches the picture
	 * through here; without it the param would be a control that looks live and
	 * changes nothing.
	 */
	setScale(scale: number): void {
		this.#engine.set_scale(scale);
	}

	/**
	 * What the renderer picked: backend, adapter and surface format.
	 *
	 * `undefined` only when no canvas is attached, which `boot` never leaves
	 * true.
	 */
	get rendererDescription(): string | undefined {
		return this.#engine.renderer_description();
	}

	/** How many draws the next `render()` will submit. */
	get drawCount(): number {
		return this.#engine.draw_count();
	}

	/**
	 * Creates a named column if it does not already exist, sized to the
	 * current slot count.
	 *
	 * `kind` is `"vec3"` (three floats per slot), `"f32"` or `"u32"`.
	 * Re-declaring a column at the same kind is a no-op and keeps what is in
	 * it; re-declaring it at a different kind throws rather than
	 * reinterpreting the column's existing bytes.
	 */
	ensureColumn(name: string, kind: "vec3" | "f32" | "u32"): void {
		this.#engine.ensure_column(name, kind);
	}

	/**
	 * A named column as a typed-array view over wasm memory: `Float32Array`
	 * for a `"vec3"` or `"f32"` column, `Uint32Array` for a `"u32"` one.
	 *
	 * The array is a **view, not a copy**, and goes stale exactly as
	 * `positions()` does — a `tick` cannot invalidate it, a `spawn` can, and so
	 * can anything that grows wasm memory. The cache is per column, so asking
	 * for two different columns never rebuilds one because the other moved.
	 * Fetch it where you use it and never store one in a field. See
	 * `docs/boundary.md`.
	 *
	 * Throws if no column of that name exists — call `ensureColumn` first.
	 */
	column(name: string): Float32Array | Uint32Array {
		const ptr = this.#engine.column_ptr(name);
		const length = this.#engine.column_len(name);
		const ints = this.#engine.column_is_ints(name);
		if (ptr === undefined || length === undefined || ints === undefined) {
			throw new Error(
				`no column named "${name}" — call ensureColumn(name, kind) first`,
			);
		}
		let cache = this.#columns.get(name);
		if (cache === undefined) {
			cache = new Column();
			this.#columns.set(name, cache);
		}
		return cache.view(this.#memory, ptr, length, ints);
	}

	/**
	 * The position column as a `Float32Array` over wasm memory: three floats
	 * per slot, indexed by the slot index `spawn` returned.
	 *
	 * A thin wrapper over `column("position")` — kept under its own name
	 * because `docs/boundary.md` and every existing caller name it, and
	 * rewriting them to the generic lookup is out of scope for the column this
	 * method now delegates to. Same staleness rule as `column()`: a `tick`
	 * cannot invalidate it, a `spawn` can, and so can anything that grows wasm
	 * memory. Fetch it where you use it and never store one in a field. See
	 * `docs/boundary.md`.
	 */
	positions(): Float32Array {
		return this.column(POSITION) as Float32Array;
	}

	/**
	 * The velocity column as a `Float32Array` over wasm memory: three floats
	 * per slot, in units per second, indexed by the same slot index
	 * `positions()` is.
	 *
	 * The batched counterpart to `setVelocity`, and the reason to prefer it:
	 * giving a whole world its velocities through the per-entity call is the
	 * crossing the column exists to avoid. Write into the view and the next
	 * `tick` integrates from it, with no call across the boundary at all.
	 *
	 * A thin wrapper over `column("velocity")` — see `positions()` for why it
	 * stays exported under its own name. Goes stale exactly as `positions()`
	 * does. Fetch it where you use it and never store one in a field. See
	 * `docs/boundary.md`.
	 */
	velocities(): Float32Array {
		return this.column(VELOCITY) as Float32Array;
	}

	/** The position of one entity, or `null` if the slot is not live. */
	positionOf(slot: number): [number, number, number] | null {
		if (slot >= this.slotCount) {
			return null;
		}
		const p = this.positions();
		const i = slot * 3;
		return [p[i] as number, p[i + 1] as number, p[i + 2] as number];
	}

	/** How many entities are live. */
	get entityCount(): number {
		return this.#engine.entity_count();
	}

	/** How many slots the position column covers, live and tombstoned alike. */
	get slotCount(): number {
		return this.#engine.slot_count();
	}

	/** How many times `tick` has been called. */
	get frameCount(): number {
		return this.#engine.frame_count();
	}

	/** Seconds of simulated time since boot. */
	get elapsed(): number {
		return this.#engine.elapsed();
	}

	/**
	 * The viewport size in physical pixels: what the engine is actually
	 * rendering at, which is what `resize` asked for unless the surface could
	 * not be configured that large.
	 */
	get viewport(): { width: number; height: number } {
		return { width: this.#engine.width(), height: this.#engine.height() };
	}
}
